# Generated by Django 6.0.5 on 2026-05-07 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                (
                    "transaccion",
                    models.CharField(
                        choices=[
                            ("Compra con saldo", "Compra con saldo"),
                            ("Compra por Mercado Pago", "Compra por Mercado Pago"),
                            ("Carga de Saldo", "Carga de Saldo"),
                            ("Devolucion", "Devolución"),
                            ("Reintegro", "Reintegro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "ordering": ["-fecha", "-hora"],
            },
        ),
        migrations.CreateModel(
            name="LogCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                ("dia_comprado", models.DateField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("turno", models.CharField(max_length=10)),
                ("menu", models.CharField(max_length=10)),
                ("tipo", models.CharField(blank=True, max_length=20)),
                ("transaccion_tipo", models.CharField(blank=True, max_length=30)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_compras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="comedor.transaccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Compra",
                "verbose_name_plural": "Logs de Compras",
                "ordering": ["-fecha", "-hora"],
            },
        ),
        migrations.CreateModel(
            name="LogCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("formato", models.CharField(default="Efectivo", max_length=20)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_cargas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas",
                        to="comedor.transaccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Carga",
                "verbose_name_plural": "Logs de Cargas",
                "ordering": ["-fecha", "-hora"],
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                ("dia_comprado", models.DateField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "turno",
                    models.CharField(
                        choices=[("manana", "Mediodía"), ("noche", "Noche")],
                        max_length=10,
                    ),
                ),
                (
                    "menu",
                    models.CharField(
                        choices=[
                            ("Basico", "Básico"),
                            ("Veggie", "Vegetariano"),
                            ("Celiaco", "Sin TACC"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=20)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("retiro", models.BooleanField(default=False)),
                (
                    "repartidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras",
                        to="comedor.transaccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "ordering": ["-dia_comprado"],
            },
        ),
    ]
