# Generated by Django 6.0.5 on 2026-06-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='hora_retiro',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
