# Generated by Django 6.0.5 on 2026-05-07 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apertura", models.DateField()),
                ("cierre", models.DateField()),
                ("vacaciones_inicio", models.DateField()),
                ("vacaciones_fin", models.DateField()),
                (
                    "dia_inicial",
                    models.IntegerField(
                        default=1, help_text="1=Lunes, 2=Martes, ... 5=Viernes"
                    ),
                ),
                (
                    "dia_final",
                    models.IntegerField(
                        default=5, help_text="1=Lunes, 2=Martes, ... 5=Viernes"
                    ),
                ),
                ("hora_final", models.TimeField(help_text="Hora de cierre de ventas")),
                ("permitir_ambos_turnos", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuración",
            },
        ),
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                ("detalle", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Feriado",
                "verbose_name_plural": "Feriados",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.IntegerField(
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                        ],
                        unique=True,
                    ),
                ),
                ("menu_basico", models.TextField(blank=True)),
                ("menu_veggie", models.TextField(blank=True)),
                ("menu_sin_tacc", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Menú",
                "verbose_name_plural": "Menús",
                "ordering": ["dia"],
            },
        ),
        migrations.CreateModel(
            name="Precio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_user",
                    models.CharField(
                        choices=[
                            ("Estudiante", "Estudiante"),
                            ("Becado", "Becado"),
                            ("Docente", "Docente"),
                            ("No Docente", "No Docente"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Precio",
                "verbose_name_plural": "Precios",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["-fecha", "-hora"],
            },
        ),
    ]
