# Generated by Django 6.0.5 on 2026-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=1000),
        ),
    ]
