# Generated by Django 6.0.5 on 2026-05-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("link", models.URLField(max_length=255)),
                (
                    "tipo_user",
                    models.CharField(
                        choices=[
                            ("Estudiante", "Estudiante"),
                            ("Docente", "Docente"),
                            ("No Docente", "No Docente"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Link de Pago",
                "verbose_name_plural": "Links de Pago",
            },
        ),
        migrations.CreateModel(
            name="CargaVirtual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("revision", "En revisión"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="revision",
                        max_length=20,
                    ),
                ),
                ("confirmacion_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmacion_vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas_confirmadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargas_virtuales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga Virtual",
                "verbose_name_plural": "Cargas Virtuales",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CompraPendiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_reference", models.CharField(max_length=255, unique=True)),
                ("datos", models.TextField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("procesada", models.BooleanField(default=False)),
                (
                    "mp_estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendiente"),
                            ("pasarela", "En pasarela"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("cancelled", "Cancelado"),
                            ("in_process", "En proceso"),
                            ("expired_by_date_cutoff", "Expirado por fecha"),
                            ("expired_by_cronjob", "Expirado por cronjob"),
                            ("cancelled_by_user", "Cancelado por usuario"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras_pendientes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra Pendiente",
                "verbose_name_plural": "Compras Pendientes",
                "ordering": ["-created_at"],
            },
        ),
    ]
