# Generated by Django 6.0.5 on 2026-05-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name='LinkPago')
    ]
