# Generated by Django 6.0.5 on 2026-05-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_remove_linkpago"),
    ]

    operations = [
        migrations.DeleteModel(name='CargaVirtual'),
    ]
